/* kategorie aktywności */

import { PROD_VARIANT_CHOICES } from "../../components/Enumerators";

export enum BB_PAKIET_CHOICES {
    NONE = PROD_VARIANT_CHOICES.NONE,
    WALK = PROD_VARIANT_CHOICES.WALK,
    RUN = PROD_VARIANT_CHOICES.RUN,
    RIDE = PROD_VARIANT_CHOICES.RIDE,
    IRON = PROD_VARIANT_CHOICES.IRON,
}

export enum BB_ACTIVITY_CHOICES {
    NONE = PROD_VARIANT_CHOICES.NONE,
    WALK = PROD_VARIANT_CHOICES.WALK,
    RUN = PROD_VARIANT_CHOICES.RUN,
    RIDE = PROD_VARIANT_CHOICES.RIDE,
}

export enum TSHIRT_CHOICES {
    TSHIRT_W = PROD_VARIANT_CHOICES.TSHIRT_W,
    TSHIRT_M = PROD_VARIANT_CHOICES.TSHIRT_M,
}

export enum ACTIVITY_STATUS_CHOICES {
    SELECTED = 0, //aktywność wybrana
    PAID = 2, // aktywność opłacona ->
}
